# Generated by Django 4.2 on 2024-10-08 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Unnamed Property')),
                ('location', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('Single Family Home', 'Single Family Home'), ('Apartment', 'Apartment'), ('Commercial', 'Commercial'), ('Land', 'Land'), ('Multi-Family', 'Multi-Family')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sqft', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('description', models.TextField()),
                ('wifi', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='highland_app.property')),
            ],
        ),
    ]
