# Generated by Django 4.2 on 2024-10-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.TextField(default='')),
                ('property_location', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('Villa', 'Villa'), ('Apartment', 'Apartment'), ('Studio Flat', 'Studio Flat')], max_length=50)),
                ('property_price', models.IntegerField(default='')),
                ('square_feet', models.IntegerField(default='')),
                ('bedrooms', models.IntegerField(default='')),
                ('property_description', models.TextField(default='')),
                ('wifi', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('car_parking', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('additional_images1', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('additional_images2', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('additional_images3', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('additional_images4', models.ImageField(blank=True, null=True, upload_to='property_images/')),
            ],
        ),
    ]
