# Generated by Django 4.2 on 2024-10-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highland_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='additional_images',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
