# Generated by Django 4.2 on 2024-10-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highland_app', '0002_property_additional_images_property_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
