# Generated by Django 4.2 on 2024-10-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highland_app', '0003_alter_property_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Villa', 'Villa'), ('Apartment', 'Apartment'), ('Studio Flat', 'Studio Flat')], max_length=50),
        ),
    ]
