# Generated by Django 4.2 on 2024-10-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highland_app', '0004_alter_property_property_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='additional_images',
            new_name='additional_images1',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='parking',
            new_name='car_parking',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='description',
            new_name='property_description',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='location',
            new_name='property_location',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='name',
            new_name='property_name',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='price',
            new_name='property_price',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='sqft',
            new_name='square_feet',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='pool',
            new_name='swimming_pool',
        ),
        migrations.AddField(
            model_name='property',
            name='additional_images10',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='additional_images2',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='additional_images3',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='additional_images4',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='additional_images5',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='additional_images6',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='additional_images7',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='additional_images8',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='additional_images9',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
