# Generated by Django 4.2 on 2024-10-09 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highland_app', '0005_rename_additional_images_property_additional_images1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='additional_images10',
        ),
        migrations.RemoveField(
            model_name='property',
            name='additional_images5',
        ),
        migrations.RemoveField(
            model_name='property',
            name='additional_images6',
        ),
        migrations.RemoveField(
            model_name='property',
            name='additional_images7',
        ),
        migrations.RemoveField(
            model_name='property',
            name='additional_images8',
        ),
        migrations.RemoveField(
            model_name='property',
            name='additional_images9',
        ),
    ]
