# Generated by Django 4.2 on 2024-10-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highland_app', '0006_remove_property_additional_images10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_price',
            field=models.TextField(default=''),
        ),
    ]
